### ISSUE TITLE
[Question] I tried to load the bert model but got an error

### ISSUE THREAD

**Issue by clclclaiggg** [TransformerLensOrg/TransformerLens#459]
My code：
model_name = "bert-base-cased"
model = HookedTransformer.from_pretrained(model_name,force_download=True)
I got an error：
KeyError                                  Traceback (most recent call last)
Cell In[25], line 6
----> 6 model = HookedTransformer.from_pretrained(model_name,force_download=True)

File E:\下载\TransformerLens-main\TransformerLens-main\transformer_lens\HookedTransformer.py:1248, in HookedTransformer.from_pretrained(cls, model_name, fold_ln, center_writing_weights, center_unembed, refactor_factored_attn_matrices, checkpoint_index, checkpoint_value, hf_model, device, n_devices, tokenizer, move_to_device, fold_value_biases, default_prepend_bos, default_padding_side, dtype, **from_pretrained_kwargs)
   1243 official_model_name = loading.get_official_model_name(model_name)
   1245 # Load the config into an HookedTransformerConfig object. If loading from a
   1246 # checkpoint, the config object will contain the information about the
   1247 # checkpoint
-> 1248 cfg = loading.get_pretrained_model_config(
   1249     official_model_name,
   1250     checkpoint_index=checkpoint_index,
   1251     checkpoint_value=checkpoint_value,
   1252     fold_ln=fold_ln,
   1253     device=device,
   1254     n_devices=n_devices,
   1255     default_prepend_bos=default_prepend_bos,
   1256     dtype=dtype,
   1257     **from_pretrained_kwargs,
   1258 )
   1260 if cfg.positional_embedding_type == "shortformer":
   1261     if fold_ln:

File E:\下载\TransformerLens-main\TransformerLens-main\transformer_lens\loading_from_pretrained.py:887, in get_pretrained_model_config(model_name, checkpoint_index, checkpoint_value, fold_ln, device, n_devices, default_prepend_bos, dtype, **kwargs)
    884 cfg_dict["dtype"] = dtype
    886 if fold_ln:
--> 887     if cfg_dict["normalization_type"] in ["LN", "LNPre"]:
    888         cfg_dict["normalization_type"] = "LNPre"
    889     else:

KeyError: 'normalization_type'

How to solve this problem? Thank you for your help.

**Comment by anrath** [comment]
```python
bert = HookedEncoder.from_pretrained("bert-base-cased")
# WARNING:root:HookedEncoder is still in beta. Please be aware that model preprocessing (e.g. LayerNorm folding) is not yet supported and backward compatibility is not guaranteed.
```

**Comment by bryce13950** [comment]
This is an issue with it not being compatible with HookedTransformer. It can be loaded unreliably in 2.x, but in 3.0, it will halt execution and explicitly inform users of the issue.
