### ISSUE TITLE
[Bug Report] `ActivationCache.apply_ln_to_stack` silently returns the resid stack for unsupported normalization types

### ISSUE THREAD

**Issue by jmsdao** [TransformerLensOrg/TransformerLens#472]
https://github.com/neelnanda-io/TransformerLens/blob/ce82675a8e89b6d5e6229a89620c843c794f3b04/transformer_lens/ActivationCache.py#L991-L993

`Meta and the RMSnorm gang has entered the chat`

**Comment by gaabrielfranco** [comment]
I am having the same issue. It should be supported by #489 (adding RMSPre in the list ["LN", "LNPre"])
