### ISSUE TITLE
[Proposal] Save and Load subgraph as dict

### ISSUE THREAD

**Issue by chris-aeviator** [TransformerLensOrg/TransformerLens#554]
### Proposal 

Add a structured representation of the subgraph/ circuit that can be saved and loaded similar to ACDC.

### Motivation
When using TransformerLens I can find subgraphs through attribution patching. However, there seems to be no easy way to use the result further downstream due to the lack of structured representation. While I can (might?) piece together all components, it is not straightforward to get the result out for plotting, archiving, re-loading at a later point.   

### Pitch

Having a save_to_dict would solve the above 'shortcomings' in working  further downstream with results gained from TL. It would enable loading a patched subgraph in a further step.

### Alternatives

I have started finding and mapping values from Attribution_Patching_Demo.ipynb but not everything is clear, as compared to ACDC this example has a finder granularity (k,v,q,..)

### Additional context

![grafik](https://github.com/neelnanda-io/TransformerLens/assets/11522213/26b8cd2c-719c-4f0c-aea2-b31c6f79b258)

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/neelnanda-io/transformerlens/issues) in the repo (**required**)

**Comment by neelnanda-io** [comment]
Can you say more about what this would look like? I'm quite confused by the
proposal. TransformerLens doesn't even have innate support for path
patching, so I don't see what it would mean to support subgraphs. Could you
eg give an example snippet of code for what you imagine using this feature
to look like, and the interface?

**Comment by ArthurConmy** [comment]
CC @UFO-101 who is building a general automated interp library. In my opinion it's better to build a library on top of TL, rather than inside TL. What advantages would there be to adding this into TL? My vibe is that the majority of TL users are not doing automated interp (even if they should be >:) ...)

**Comment by neelnanda-io** [comment]
+1 to Arthur, I think this would be a cool thing for someone to build on top

**Comment by UFO-101** [comment]
FYI the library is now released: https://ufo-101.github.io/auto-circuit/
Post explaining how it works: https://www.lesswrong.com/posts/caZ3yR5GnzbZe2yJ3/how-to-do-patching-fast
