### ISSUE TITLE
[Bug Report] Attn Result hook not working

### ISSUE THREAD

**Issue by oliveradk** [TransformerLensOrg/TransformerLens#659]
When use_attn_result is set to True, HookedTransformers error on the forward pass

<img width="900" alt="Screenshot 2024-07-08 at 12 59 40 PM" src="https://github.com/TransformerLensOrg/TransformerLens/assets/40397426/32dec2ea-48a7-4848-adbb-60191208bb38">

**System Info**
Describe the characteristic of your environment:
Transformer lens installed via poetry 
MacOS
Python3.10
einops0.7.0

**Additional context**
I believe the issue was introduced by this commit https://github.com/TransformerLensOrg/TransformerLens/commit/e9d9cb241ab39716cd8706db07c513f1bc1728bf#diff-7fab54dae26fa1f2b8256aa8707fd3402e31ca689db3aece4827aa1e2a8199d9

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/TransformerLensOrg/TransformerLens/issues) in the repo (**required**)

**Comment by bryce13950** [comment]
The segment you changed was changed since you opened your issue & PR. I merged the change into your PR, and it looks like your test is passing with the most recent change. Can you verify your use still works with the most recent changes?

**Comment by oliveradk** [comment]
Yes, my use still works, thank you!
