### ISSUE TITLE
[Bug Report] Einops shape error when `use_attn_result = True` 

### ISSUE THREAD

**Issue by dtch1997** [TransformerLensOrg/TransformerLens#667]
**Describe the bug**
Setting `use_attn_result = True` results in an error when running the model due to an `einops` shape error. 

**Code example**
Minimal working example here: https://colab.research.google.com/drive/1vaPKk-C2xcvCGZmwGePY044nlwI5tFcL?usp=sharing

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/TransformerLensOrg/TransformerLens/issues) in the repo (**required**)

**Comment by bryce13950** [comment]
Fixed in 2.2.1. Thanks for the report!
