### ISSUE TITLE
[Bug Report] Backward hooks are broken as of v2.0.0

### ISSUE THREAD

**Issue by chanind** [TransformerLensOrg/TransformerLens#672]
**Describe the bug**
It looks like as part of a change to add pyright type checking in #607 ([line 119](https://github.com/TransformerLensOrg/TransformerLens/pull/607/files#diff-85fafabc38ed61e857e7db5df426fe1696f7a1dbe3a9c532ca8dff4718d0193dR119)), backwards hooks were changed from being added with `register_full_backward_hook()` to `register_backward_hook()`.

I don't know if this was intentional, but these are not the same function, and [register_backward_hook is deprecated and should not be used](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.register_backward_hook). Since this change, a hook I had added no longer works.

**Code example**
The code below will run fine on TLens < 2.0.0
```python
model = HookedTransformer.from_pretrained("gpt2")

def bwd_hook(output_grads, hook):
    return (output_grads, )

with model.hooks(bwd_hooks=[("blocks.0.hook_resid_post", bwd_hook)]):
    out = model("hi")
    out.sum().backward()
```

On TLens >= 2.0.0, the following error is raised:

```
RuntimeError: hook '<function bwd_hook at 0x7fc89a77b370>' has returned an incorrect number of values (got 1, but expected 2)
```

This error can be seen in https://colab.research.google.com/drive/1JG6SPwKL3If4p_pw1b1nquAHVF3uNaEi?usp=sharing

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by bryce13950** [comment]
Fixed in 2.2.2
