### ISSUE TITLE
[Proposal] Demo and Tutorial on Patchscopes and "Patching + Generation"

### ISSUE THREAD

**Issue by HenryCai11** [TransformerLensOrg/TransformerLens#680]
### Proposal 

UPDATE: Demo and Tutorial on Patchscopes and "Patching + Generation"

DEPRECATED: Replication of the original causal tracing from the ROME paper.

### Motivation

I found that the original causal tracing method hasn't been supported here, and I think it has some advantages over the current activation patching method. For example, corruption with Gaussian noise might preserve more semantic information from the original sentence than corruption by changing words.

### Pitch

To replicate the original causal tracing method from the ROME paper ([https://arxiv.org/abs/2202.05262](https://arxiv.org/abs/2202.05262))

### Alternatives

I also consider replicating the Patchscope here, which is also mentioned in issue #500. Since Patchscope can be considered as a more general framework for this kind of patching/intervention-based methods, implementing it here can also make causal tracing available. I'd like to open another issue for the replication of Patchscope later.

### Additional context

I've implemented a version locally, and would like to put some examples here, comparing results from my implementation and from the original implementation.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/TransformerLensOrg/Transformerlens/issues) in the repo (**required**)

**Comment by HenryCai11** [comment]
@neelnanda-io Thanks for the clarification! Yeah, I've roughly tried combining patching and generation, and found that there might be several subtleties need to be concerned. I'd like to contribute a tutorial on it and further an implementation of Patchscopes.

Maybe I'll just use this thread for a "tutorial and demo on patching + generation and Patchscopes", and make PR(s) later.

**Comment by bryce13950** [comment]
@HenryCai11 Do you need any help getting started with this? If you want to put the demo together, I would be happy to walk you through a couple steps in the process. Any new demos added to the project need to be covered by the CI, so there are a couple nuances to how they should be put together. A lot of how to do this can be seen within other demos that are currently covered, but I am happy to walk through any specific questions you may have on how to get started.

**Comment by HenryCai11** [comment]
> @HenryCai11 Do you need any help getting started with this? If you want to put the demo together, I would be happy to walk you through a couple steps in the process. Any new demos added to the project need to be covered by the CI, so there are a couple nuances to how they should be put together. A lot of how to do this can be seen within other demos that are currently covered, but I am happy to walk through any specific questions you may have on how to get started.

Thanks @bryce13950 ! I have now started to write up the demos. I'll see if it'll be more convenient to put them together, otherwise I think separating them would be nice.

**Comment by HenryCai11** [comment]
Hi @bryce13950 , I've made a pull request #692. I finally decided to put both of them in the same notebook and added clear comments of how to implement them. I also passed the notebook test locally. Please let me know if there's anything else that I need to do. Thanks!
