### ISSUE TITLE
[Proposal] Warn people when trying to load t5 into HookedTransformer

### ISSUE THREAD

**Issue by bryce13950** [TransformerLensOrg/TransformerLens#726]
### Proposal 

T5 models need to be loaded using `HookedEncoderDecoder`, but there is nothing to inform the user if they try to use the models via `HookedTransformer`. Instead, TransformerLens tries to run using this model, and ends up failing out almost instantly with very generic errors. We should add a little error message here to direct someone to `HookedTransformer`.

### Motivation

To make TransformerLens a little bit easier to use.

### Pitch

Stop execution immediately and direct users to the correct functionality.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/TransformerLensOrg/Transformerlens/issues) in the repo (**required**)

**Comment by vatsalrathod16** [comment]
I can work on this issue

**Comment by bryce13950** [comment]
@vatsalrathod16 I actually created this for @diondredroidios who has expressed interest in helping with the project. @vatsalrathod16 if you are interested in getting involved with some tasks, I actually have a lot that need to be completed which are not documented right now. 

I am in the middle of auditing all officially supported models, and in the process I have found quite a few compatibility issues that need to be addressed. I haven't put anything in GitHub yet, since I need to do some verification of when issues were introduced, and if the problems I am seeing are actually issues, or if they are expected behavior. If you would like something to help with, you could be a great help on that side of researching some of these model issues, and then figuring out how to resolve some of them. If you are on the slack slack channel @Bryce Meyer. If you are not yet there, let me know and I can get you setup.

**Comment by vatsalrathod16** [comment]
I would like to contribute and I am not on the slack channel.

**Comment by bryce13950** [comment]
@vatsalrathod16 Jump on the channel! https://join.slack.com/t/opensourcemechanistic/shared_invite/zt-2r9l0ajhx-hvNJJaKi0NFqYrJsQF3ppw If you want to throw something on my calendar for next week http://calendly.com/bryce-c7e/30min, we can talk a bit about your background, what is currently important to complete, and I can find something that will fit well in your skillset, which will benefit the project.
