### ISSUE TITLE
Fine tune model and using this framework

### ISSUE THREAD

**Issue by nitay16** [TransformerLensOrg/TransformerLens#730]
Hi, I a finetuned model with lora that I trained with the trainer of huggin face. can my finetuned model with this framework? I tried to load it but I saw that we load only the models that are in the list.
Many thanks in advance

**Comment by bryce13950** [comment]
Can you provide a little bit more information? If the model you fine tuned is based on a model we already support, then you should hypothetically be able to load the model with the param `hf_model`. For the model id, you simply want to put the original model name of which you based your work. If the model you based your work on is not supported, if you still want to share the model with me, I can see if it is something that we would be willing to add.

**Comment by nitay16** [comment]
The model I fine tuned is Llama 7b chat. I saw that the framework supports this model. Specifically the fine tuned I did with Lora with the Peft library. Is it still possible to use the framework with my finetuned model?

**Comment by bryce13950** [comment]
Can you upload the model somewhere, and provide me with a link to it? i.e. google docs, dropbox, or any other file sharing service? If I can get your model downloaded, I am happy to try and experiment, to see if I can figure out a configuration needed to get your model loaded into TransformerLens. Hypothetically, it should be possible with passing in the current model id. What is the exact model id that you worked with? Was it `meta-llama/Llama-2-7b-chat-hf`?
