### ISSUE TITLE
[Proposal] Add example of collecting activations from a single layer.

### ISSUE THREAD

**Issue by adamkarvonen** [TransformerLensOrg/TransformerLens#746]
### Proposal 

In the README or a tutorial, add an example of how to collect activations from a single layer of a model.

### Motivation

run_with_cache() uses a ton of memory. Often, for contrastive activations, linear probing, or SAEs, we only need activations from a single layer, which should require much less memory. I couldn't easily find an example of how to do this, and I believe this has somewhat contributed to a misconception that TransformerLens has high memory usage.

### Pitch

Add an example of collecting activations from a single layer to the README or a tutorial. Make it somewhat easy to find. I think it should only be a few lines of code.

After playing around with TransformerLens, this is the solution that I had came up with, but there may be a better way. https://github.com/adamkarvonen/SAE_Bench_Template/blob/main/utils/activation_collection.py#L46

### Alternatives

A clear and concise description of any alternative solutions or features you've considered, if any.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/TransformerLensOrg/Transformerlens/issues) in the repo (**required**)

**Comment by neelnanda-io** [comment]
Great idea, I'd love to have this contributed!

Your implementation seems reasonable. I personally tend to have an empty
list, and a hook that appends acts to it (and then concatenate them at the
end). It's important to emphasise the need for torch.no_grad or
torch.set_grad_enabled(False) (which I see you use)

**Comment by adamkarvonen** [comment]
Sounds good, I will submit a pull request with a brief section added to this notebook. https://github.com/TransformerLensOrg/TransformerLens/blob/main/demos/Main_Demo.ipynb

**Comment by bryce13950** [comment]
How's it going with this?

**Comment by adamkarvonen** [comment]
I'd gotten a bit swamped with deadlines over the last couple weeks. I can take a look at this next week unless someone else wants to do it before then.

**Comment by bryce13950** [comment]
If you have the time it would be much appreciated. We have a big update coming up that I am currently thoroughly testing. If you have some time next week to do this, I can work it into the next update.

**Comment by adamkarvonen** [comment]
Here is a pull request. I added the demo cell at what I thought was a reasonable location, but feel free to move it around, change the wording, etc.

https://github.com/TransformerLensOrg/TransformerLens/pull/807
