### ISSUE TITLE
[Bug Report] microsoft/Phi-3.5-mini-instruct could not be loaded into Transformer_Lens Kernel get killed.

### ISSUE THREAD

**Issue by prof-schacht** [TransformerLensOrg/TransformerLens#748]
Hi

I tried to load the new microsoft/Phi-3.5-mini-instruct model into a HookedTransformer. 
But the process always kills the kernel without any error messages. 

CUDA OOM is not the case. I try to load it into a H100 80 GB. 
Also I checked if there is any system resource issue. But also this is not the case. 

I change the loading_from_pretrained.py to add the     "microsoft/Phi-3.5-mini-instruct"
Checked if there are any differences between the other PHI3CausualLLMs to the 3.5.

The differences are: 

Parameter	Differences	Details
3	_commit_hash	Yes	af0dfb8029e8a74545d0736d30cb6b58d2f0f3f0 vs 0a...
30	max_position_embeddings	Yes	131072 vs 4096
51	transformers_version	Yes	4.43.3 vs 4.40.2
52	_name_or_path	Yes	microsoft/Phi-3.5-mini-instruct vs microsoft/P...
64	sliding_window	Yes	262144 vs 2047
73	rope_scaling	Yes	{'long_factor': [1.0800000429153442, 1.1100000...
76	auto_map	Yes	{'AutoConfig': 'microsoft/Phi-3.5-mini-instruc...

I would expect that the model should load just fine. 
Or did I missed something?

**Comment by neelnanda-io** [comment]
Killing the kernel with no error message is odd, and typically means you've exceeded all CPU RAM. Exceeding all GPU RAM will give you a CUDA error, though I think TransformerLens may initialise on the CPU?

I think what's happening is that the attention class stores a mask variable that's max_ctx by max_ctx. Your max_ctx is 131072, which is much higher, so the square is about 17B, per head, is enough to blow through the memory.

Reducing the max_ctx is the obvious fix here, if you don't intend to use the massive context (feel free to submit a PR for this, or just edit it locally yourself). Longer term, we should really stop storing the mask variable and instead instantiate it at inference time, so we don't have this silly memory issue.

**Comment by bryce13950** [comment]
Try setting `max_ctx ` to 2048. Normally that allows the model to load without additional memory issues, and it should not affect the performance of the model.

**Comment by prof-schacht** [comment]
Where should I set this parameter. 

I tried it like this:
from transformers import AutoModelForCausalLM, AutoTokenizer

hf_model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3-mini-4k-instruct", trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-4k-instruct", trust_remote_code=True)

from transformer_lens import HookedTransformer, HookedTransformerConfig

cfg = HookedTransformerConfig.from_dict({
    "d_model": hf_model.config.hidden_size,
    "d_head": hf_model.config.hidden_size // hf_model.config.num_attention_heads,
    "n_heads": hf_model.config.num_attention_heads,
    "d_mlp": hf_model.config.intermediate_size,
    "n_layers": hf_model.config.num_hidden_layers,
    "n_ctx": 2048,  # Set this to your desired context length
    "d_vocab": hf_model.config.vocab_size,
    "act_fn": hf_model.config.hidden_act,
    "normalization_type": "LNPre",  # Phi models use LayerNorm
    "device": "cuda:0"
})

model = HookedTransformer(cfg, tokenizer=tokenizer)
model.load_and_process_state_dict(hf_model.state_dict())

But this os not working. 
KeyError: 'blocks.0.ln1.b'

Is there a more convenient way to do it?

**Comment by prof-schacht** [comment]
I got it loaded with this command:
model = HookedTransformer.from_pretrained("microsoft/Phi-3.5-mini-instruct", device="cuda:0", max_position_embeddings=2048)
