### ISSUE TITLE
[Bug Report] Error on import due to missing `typeguard` dependency

### ISSUE THREAD

**Issue by chanind** [TransformerLensOrg/TransformerLens#785]
**Describe the bug**
Transformerlens imports `typeguard` in SVDInterpreter.py, but this package is not in the list of dependencies for transformer_lens. As a result, this now errors until the user isntalls `typeguard`

It looks like the only reason this didn't error previously is that JaxTyping had `typeguard` as a dependency, but that was removed recently: https://github.com/patrick-kidger/jaxtyping/commit/72becb4951067dada605e085af2ff7bc09be4a11

**Code example**
This is currently erroring in SAELens tests, but running the following line should trigger the error:

```python
from transformer_lens.ActivationCache import ActivationCache
```

**System Info**
Describe the characteristic of your environment:
 * Most recent version of all dependencies, installed in Github Actions

**Additional context**
Sample error in a run failure: https://github.com/jbloomAus/SAELens/actions/runs/11909882063/job/33188172274?pr=370

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/TransformerLensOrg/TransformerLens/issues) in the repo (**required**)

**Comment by bryce13950** [comment]
All set!
