### ISSUE TITLE
[Question] What is stanford-gpt2-small-a?

### ISSUE THREAD

**Issue by leo1oel** [TransformerLensOrg/TransformerLens#805]
### Question

1. Is there any difference between stanford-gpt2-small-a and stanford-gpt2-small-b, stanford-gpt2-small-c as stated in the documentation?

**Comment by bryce13950** [comment]
Those are simply aliases with the following mappings... 

`stanford-gpt2-small-a` -> `stanford-crfm/alias-gpt2-small-x21`
`stanford-gpt2-small-b` -> `stanford-crfm/battlestar-gpt2-small-x49`
`stanford-gpt2-small-b` -> `stanford-crfm/caprica-gpt2-small-x81`

The details of this are found in `loading_from_pretrained.py` around line 500. If you ever have questions about model references that do not match official hugging face names, ctrl/cmd+f in `loading_from_pretrained.py` will shed some light on it relatively quickly.
